--
-- PostgreSQL database dump
--

\restrict pmaGvEiCNdnLA5NU4LaTXxqRTf8hlXTw8d7fYViTWSMM1fdA78DJzpjpNhZSNhO

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat (
    id integer NOT NULL,
    activo boolean NOT NULL,
    completado boolean,
    estado character varying(255),
    fecha_creacion timestamp(6) without time zone,
    fecha_devolucion timestamp(6) without time zone,
    fecha_quedada timestamp(6) without time zone,
    ubicacion character varying(100),
    id_producto1 integer NOT NULL,
    id_producto2 integer,
    id_usuario1 integer NOT NULL,
    id_usuario2 integer NOT NULL,
    confirmado1 boolean DEFAULT false,
    confirmado2 boolean DEFAULT false,
    CONSTRAINT chat_estado_check CHECK (((estado)::text = ANY (ARRAY[('pendiente'::character varying)::text, ('aceptado'::character varying)::text, ('devuelto'::character varying)::text])))
);


ALTER TABLE public.chat OWNER TO postgres;

--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorito (
    id_producto integer NOT NULL,
    id_usuario integer NOT NULL
);


ALTER TABLE public.favorito OWNER TO postgres;

--
-- Name: imagen_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imagen_producto (
    id integer NOT NULL,
    orden integer,
    url_img character varying(500) NOT NULL,
    id_producto integer NOT NULL
);


ALTER TABLE public.imagen_producto OWNER TO postgres;

--
-- Name: imagen_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imagen_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagen_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensaje; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensaje (
    id integer NOT NULL,
    contenido text NOT NULL,
    fecha_envio timestamp(6) without time zone,
    leido boolean NOT NULL,
    id_chat integer NOT NULL,
    id_remitente integer DEFAULT 0 NOT NULL,
    tipo character varying(20) DEFAULT 'TEXTO'::character varying NOT NULL,
    aceptado boolean
);


ALTER TABLE public.mensaje OWNER TO postgres;

--
-- Name: mensaje_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id integer NOT NULL,
    activo boolean NOT NULL,
    categoria character varying(20) NOT NULL,
    color character varying(20),
    descripcion character varying(500),
    estado character varying(20) NOT NULL,
    estilo character varying(30) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    fecha_devolucion timestamp(6) without time zone,
    marca character varying(20) NOT NULL,
    precio numeric(10,2),
    talla character varying(4) NOT NULL,
    tipo character varying(50) NOT NULL,
    titulo character varying(50) NOT NULL,
    id_usuario integer NOT NULL,
    CONSTRAINT producto_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('intercambio'::character varying)::text, ('prestamo'::character varying)::text])))
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- Name: producto_historico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_historico (
    id integer NOT NULL,
    accion character varying(255) NOT NULL,
    categoria character varying(20),
    color character varying(20),
    descripcion character varying(500),
    estilo character varying(30),
    fecha_creacion timestamp(6) without time zone,
    fecha_devolucion timestamp(6) without time zone,
    marca character varying(20),
    precio numeric(38,2),
    talla character varying(4),
    tipo character varying(255) NOT NULL,
    titulo character varying(50),
    id_producto integer,
    id_usuario integer,
    CONSTRAINT producto_historico_accion_check CHECK (((accion)::text = ANY (ARRAY[('CREADO'::character varying)::text, ('ACTUALIZADO'::character varying)::text, ('BORRADO'::character varying)::text, ('DESACTIVADO'::character varying)::text]))),
    CONSTRAINT producto_historico_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('intercambio'::character varying)::text, ('prestamo'::character varying)::text])))
);


ALTER TABLE public.producto_historico OWNER TO postgres;

--
-- Name: producto_historico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_historico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_historico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raiting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.raiting (
    puntuacion integer,
    id_puntuado integer NOT NULL,
    id_puntuador integer NOT NULL
);


ALTER TABLE public.raiting OWNER TO postgres;

--
-- Name: seguidor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguidor (
    id_seguido integer NOT NULL,
    id_seguidor integer NOT NULL
);


ALTER TABLE public.seguidor OWNER TO postgres;

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    apellidos character varying(50) NOT NULL,
    descripcion character varying(500),
    direccion character varying(500),
    email character varying(50) NOT NULL,
    estilo character varying(30),
    nombre character varying(20) NOT NULL,
    password character varying(100) NOT NULL,
    t_calzado integer,
    t_camiseta character varying(4),
    t_pantalon integer,
    url_img character varying(500)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: chat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat (id, activo, completado, estado, fecha_creacion, fecha_devolucion, fecha_quedada, ubicacion, id_producto1, id_producto2, id_usuario1, id_usuario2, confirmado1, confirmado2) FROM stdin;
2	t	t	aceptado	\N	\N	2026-07-15 18:00:00	Plaza Mayor, Madrid	1	5	3	1	t	t
3	t	f	pendiente	\N	\N	\N	\N	5	\N	4	3	f	f
4	t	f	pendiente	\N	2026-07-20 17:00:00	2026-06-20 17:00:00	Paseo de Gracia, Barcelona	7	\N	2	4	f	f
5	t	t	aceptado	2026-06-17 22:50:57.327686	2026-06-30 22:51:00	2026-06-26 22:50:00	sevilla	10	1	1	5	t	t
\.


--
-- Data for Name: favorito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.favorito (id_producto, id_usuario) FROM stdin;
5	1
1	2
9	2
2	3
7	3
3	4
5	4
1	5
6	5
6	1
\.


--
-- Data for Name: imagen_producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.imagen_producto (id, orden, url_img, id_producto) FROM stdin;
1	1	https://res.cloudinary.com/dgucb1e4a/image/upload/camisa_jzr0ui	1
2	1	https://res.cloudinary.com/dgucb1e4a/image/upload/chupa-cuero_qai0pj	2
3	1	https://res.cloudinary.com/dgucb1e4a/image/upload/vestido-verde_yvex93	3
5	1	https://res.cloudinary.com/dgucb1e4a/image/upload/zapatos-nike_jovv2i	5
7	1	https://res.cloudinary.com/dgucb1e4a/image/upload/chaqueta-marron_xpgzkm	7
8	1	https://res.cloudinary.com/dgucb1e4a/image/upload/41p3AEqv7DL._AC_SY580_-2872398340_kg5uxb	8
9	1	https://res.cloudinary.com/dgucb1e4a/image/upload/chaqueta-verde_uxdywf	9
10	1	https://res.cloudinary.com/dgucb1e4a/image/upload/51helrDdfzL._AC_SY580_-2926793799_oxy67i	10
4	1	https://res.cloudinary.com/dgucb1e4a/image/upload/cuero_jszhr1	4
6	1	https://res.cloudinary.com/dgucb1e4a/image/upload/59feb64c1600b55b2319c156b044949a-248048753_jbngc1	6
11	2	https://res.cloudinary.com/dgucb1e4a/image/upload/67083343_452771348909116_5694924955716681728_n_p1prl9	7
\.


--
-- Data for Name: mensaje; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mensaje (id, contenido, fecha_envio, leido, id_chat, id_remitente, tipo, aceptado) FROM stdin;
7	Hola! Me interesa tu camisa. Yo tengo zapatillas Nike 44 para intercambiar.	\N	t	2	3	TEXTO	\N
8	Perfecto, me interesan las zapatillas. Propón fecha y lugar.	\N	t	2	1	TEXTO	\N
9	2026-07-15T18:00:00	\N	t	2	3	FECHA	t
10	Plaza Mayor, Madrid	\N	t	2	3	UBICACION	t
11	2026-07-22T18:00:00	\N	t	2	3	FECHA_DEVOLUCION	t
12	5	\N	t	2	1	PRODUCTO	t
13	Carlos ha confirmado el intercambio. Confirma tu tambien!	\N	t	2	3	TEXTO	\N
14	Luis ha confirmado el intercambio. Confirma tu tambien!	\N	t	2	1	TEXTO	\N
15	Hola Carlos! Esas zapatillas me encantan. Las cambias por algo?	\N	t	3	4	TEXTO	\N
17	Hola Marta! Me encanta tu chaqueta marron. La alquilaria para una boda.	\N	t	4	2	TEXTO	\N
18	Claro! Es perfecta para eventos. Cuando la necesitarias?	\N	t	4	4	TEXTO	\N
19	Para el 20 de junio. Podria ser?	\N	t	4	2	TEXTO	\N
20	2026-06-20T17:00:00	\N	t	4	2	FECHA	f
21	Paseo de Gracia, Barcelona	\N	f	4	2	UBICACION	f
22	2026-07-20T17:00:00	\N	f	4	2	FECHA_DEVOLUCION	f
16	Hola Marta! Cuentame que tienes, soy bastante selectivo con el calzado.	\N	t	3	3	TEXTO	\N
23	2026-06-26T22:50:00	2026-06-17 22:51:02.553986	t	5	1	FECHA	t
24	2026-06-30T22:51:00	2026-06-17 22:51:07.597442	t	5	1	FECHA_DEVOLUCION	t
25	sevilla	2026-06-17 22:51:23.259985	t	5	1	UBICACION	t
26	1	2026-06-17 22:54:18.595756	t	5	5	PRODUCTO	t
27	✅ Luis ha confirmado el intercambio. ¡Confírmalo tú también para completarlo!	2026-06-17 22:54:37.848054	t	5	1	TEXTO	\N
28	✅ Javier ha confirmado el intercambio. ¡Confírmalo tú también para completarlo!	2026-06-17 22:54:41.306181	t	5	5	TEXTO	\N
\.


--
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto (id, activo, categoria, color, descripcion, estado, estilo, fecha_creacion, fecha_devolucion, marca, precio, talla, tipo, titulo, id_usuario) FROM stdin;
2	t	Ropa	Negro	Chaqueta de cuero genuino, estilo biker. En perfecto estado.	Como nuevo	Informal	\N	\N	Levis	25.00	M	prestamo	Chupa de cuero	1
3	t	Ropa	Verde	Vestido midi de color verde esmeralda, ideal para eventos. Talla S.	Como nuevo	Formal	\N	\N	Mango	\N	S	intercambio	Vestido verde	2
5	t	Calzado	Blanco	Nike Air Force 1 blancas, talla 44. En muy buen estado.	Bueno	Deportivo	\N	\N	Nike	\N	44	intercambio	Zapatillas Nike	3
8	t	Ropa	Negro	Falda midi de pliegues color negro, elegante y facil de combinar.	Nuevo	Formal	\N	\N	H&M	\N	S	intercambio	Falda midi plisada	4
10	f	Accesorios	Azul	Gorra azul marino ajustable, bordado frontal. Nunca usada.	Nuevo	Deportivo	\N	\N	Nike	\N	U	intercambio	Gorra azul	5
1	f	Ropa	Multicolor	Camisa de manga corta estampada, perfecta para verano. Usada pocas veces.	Bueno	Casual	\N	\N	Nike	\N	M	intercambio	Camisa estampada	1
4	t	Ropa	Azul	Pantalones de cuero de corte recto, clasico y versatil. Muy poco uso.	Bueno	Casual	\N	\N	Levis	\N	S	intercambio	Pantalones de cuero	2
6	t	Ropa	Negro	Sudadera con capucha de algodon grueso. Muy comoda para entrenar.	Bueno	Deportivo	\N	\N	Nike	10.00	L	prestamo	Sudadera negra	3
7	t	Ropa	Marron	Chaqueta entallada color camel, perfecta para primavera.	Como nuevo	Casual	\N	\N	Zara	15.00	S	prestamo	Chaqueta marron	5
9	t	Ropa	Verde	Chaqueta verde militar de tela resistente, estilo cargo.	Bueno	Informal	\N	\N	Pull&Bear	\N	L	intercambio	Chaqueta verde	4
\.


--
-- Data for Name: producto_historico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto_historico (id, accion, categoria, color, descripcion, estilo, fecha_creacion, fecha_devolucion, marca, precio, talla, tipo, titulo, id_producto, id_usuario) FROM stdin;
\.


--
-- Data for Name: raiting; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.raiting (puntuacion, id_puntuado, id_puntuador) FROM stdin;
5	1	2
4	1	3
5	2	1
4	2	4
4	3	1
5	3	2
3	4	3
5	4	5
4	5	1
4	5	2
5	1	5
\.


--
-- Data for Name: seguidor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seguidor (id_seguido, id_seguidor) FROM stdin;
2	1
1	2
4	2
1	3
5	3
2	4
3	4
1	5
4	5
5	1
3	1
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, apellidos, descripcion, direccion, email, estilo, nombre, password, t_calzado, t_camiseta, t_pantalon, url_img) FROM stdin;
3	Ruiz	Estilo deportivo, mucho Nike y Adidas.	Paseo del Prado 3, Madrid	carlos@swapcloset.com	Deportivo	Carlos	$2b$10$F2z6FhLecS90mWqzig8A7.x5LBwH0lYYrEaE5McAFdVeWtd9vr5HS	44	L	44	https://res.cloudinary.com/dgucb1e4a/image/upload/img-perfil-2_dw2egb
4	Lopez	Fan de Zara y Mango. Renuevo armario a menudo.	Gran Via 18, Bilbao	marta@swapcloset.com	Casual	Marta	$2b$10$JxGbDtv/GVzuKh/bKTLJMu.8Ensy0oJtC5Fe5Xsm0dLNeps3N1Ooq	38	S	36	https://res.cloudinary.com/dgucb1e4a/image/upload/perfil-4_c4bjl0
5	Sanchez	Coleccionista de chaquetas.	Calle Serrano 44, Madrid	javier@swapcloset.com	Informal	Javier	$2b$10$NlppXjucBUtD5DQ8PITWuOzjv8cMV5/f/hmIbVVyClpDX9ezto5US	42	L	42	https://res.cloudinary.com/dgucb1e4a/image/upload/img-perfil-3_ot5per
2	Gonzalez	Me encanta la moda formal y los vestidos.	Avenida de la Paz 5, Barcelona	sara@swapcloset.com	Formal	Sara	$2b$10$5C3br7mG3TyLw89uIjmnIu4N2CoCNT7BfMKSU8GpiYmwSxxiUmGfS	37	S	38	https://res.cloudinary.com/dgucb1e4a/image/upload/img-perfil-10_lqwhel
1	Martinez	Amante de la moda casual y los intercambios.	Calle Mayor 12, Madrid	luis@swapcloset.com	Casual	Luis	$2b$10$vCQgQE.1.141zCpL5udOz.5X4fIfQLUR0o9ValOjmPasyGdDb5CVu	43	M	42	https://res.cloudinary.com/dgucb1e4a/image/upload/perfillll_deeew4
\.


--
-- Name: chat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_id_seq', 5, true);


--
-- Name: imagen_producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.imagen_producto_id_seq', 11, true);


--
-- Name: mensaje_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensaje_id_seq', 28, true);


--
-- Name: producto_historico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_historico_id_seq', 1, false);


--
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_id_seq', 10, true);


--
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 5, true);


--
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- Name: favorito favorito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_pkey PRIMARY KEY (id_producto, id_usuario);


--
-- Name: imagen_producto imagen_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagen_producto
    ADD CONSTRAINT imagen_producto_pkey PRIMARY KEY (id);


--
-- Name: mensaje mensaje_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensaje
    ADD CONSTRAINT mensaje_pkey PRIMARY KEY (id);


--
-- Name: producto_historico producto_historico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_historico
    ADD CONSTRAINT producto_historico_pkey PRIMARY KEY (id);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- Name: raiting raiting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raiting
    ADD CONSTRAINT raiting_pkey PRIMARY KEY (id_puntuado, id_puntuador);


--
-- Name: seguidor seguidor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguidor
    ADD CONSTRAINT seguidor_pkey PRIMARY KEY (id_seguido, id_seguidor);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: chat fk47e8sscmkvy9a9kqilweqy3gd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk47e8sscmkvy9a9kqilweqy3gd FOREIGN KEY (id_producto2) REFERENCES public.producto(id);


--
-- Name: chat fk49vc48lf6aievxgo6kc6kmbap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk49vc48lf6aievxgo6kc6kmbap FOREIGN KEY (id_usuario1) REFERENCES public.usuario(id);


--
-- Name: favorito fk5vmlgfa4nyi848sknxb237yjt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT fk5vmlgfa4nyi848sknxb237yjt FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- Name: raiting fk6uhh530phlkfvhd2ivl0t8jeh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raiting
    ADD CONSTRAINT fk6uhh530phlkfvhd2ivl0t8jeh FOREIGN KEY (id_puntuado) REFERENCES public.usuario(id);


--
-- Name: seguidor fk7m5yeae46r7kidkh745j83wt1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguidor
    ADD CONSTRAINT fk7m5yeae46r7kidkh745j83wt1 FOREIGN KEY (id_seguido) REFERENCES public.usuario(id);


--
-- Name: producto_historico fk8n6mcd4dlkbyiu41ayt3qgxfr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_historico
    ADD CONSTRAINT fk8n6mcd4dlkbyiu41ayt3qgxfr FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- Name: producto_historico fkb1kio7fwgafb6foordgu6vlj0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_historico
    ADD CONSTRAINT fkb1kio7fwgafb6foordgu6vlj0 FOREIGN KEY (id_producto) REFERENCES public.producto(id);


--
-- Name: mensaje fke19chdnxesv3itlf0v128hmrp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensaje
    ADD CONSTRAINT fke19chdnxesv3itlf0v128hmrp FOREIGN KEY (id_chat) REFERENCES public.chat(id);


--
-- Name: imagen_producto fkh1jspkou01bp4y2q0ynq9el6k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagen_producto
    ADD CONSTRAINT fkh1jspkou01bp4y2q0ynq9el6k FOREIGN KEY (id_producto) REFERENCES public.producto(id);


--
-- Name: chat fkj8jtvjv92axld94ivb4j92tk2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fkj8jtvjv92axld94ivb4j92tk2 FOREIGN KEY (id_usuario2) REFERENCES public.usuario(id);


--
-- Name: producto fkjhnhu11h92o6gjd4eha5xux79; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkjhnhu11h92o6gjd4eha5xux79 FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- Name: chat fklup4frpvgeol2gatg4b74ism4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fklup4frpvgeol2gatg4b74ism4 FOREIGN KEY (id_producto1) REFERENCES public.producto(id);


--
-- Name: favorito fkq7wolabg1djamjksigfuljss2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT fkq7wolabg1djamjksigfuljss2 FOREIGN KEY (id_producto) REFERENCES public.producto(id);


--
-- Name: raiting fksb5xtm5jt7u99dajtnj8lvimi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raiting
    ADD CONSTRAINT fksb5xtm5jt7u99dajtnj8lvimi FOREIGN KEY (id_puntuador) REFERENCES public.usuario(id);


--
-- Name: seguidor fkshauxuejxaiguxm7jlk5bpuej; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguidor
    ADD CONSTRAINT fkshauxuejxaiguxm7jlk5bpuej FOREIGN KEY (id_seguidor) REFERENCES public.usuario(id);


--
-- PostgreSQL database dump complete
--

\unrestrict pmaGvEiCNdnLA5NU4LaTXxqRTf8hlXTw8d7fYViTWSMM1fdA78DJzpjpNhZSNhO

