--
-- PostgreSQL database dump
--

\restrict ESYSQx47dS4pld5hjnYvkGDYaxEaelKjtLcg6uu0l8gUgz6KUiu5c1CgvZygD0U

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat (
    id integer NOT NULL,
    activo boolean NOT NULL,
    completado boolean,
    estado character varying(255),
    fecha_creacion timestamp(6) without time zone,
    fecha_devolucion timestamp(6) without time zone,
    fecha_quedada timestamp(6) without time zone,
    ubicacion character varying(100),
    id_producto1 integer NOT NULL,
    id_producto2 integer,
    id_usuario1 integer NOT NULL,
    id_usuario2 integer NOT NULL,
    CONSTRAINT chat_estado_check CHECK (((estado)::text = ANY (ARRAY[('pendiente'::character varying)::text, ('aceptado'::character varying)::text, ('devuelto'::character varying)::text])))
);


ALTER TABLE public.chat OWNER TO postgres;

--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorito (
    id_producto integer NOT NULL,
    id_usuario integer NOT NULL
);


ALTER TABLE public.favorito OWNER TO postgres;

--
-- Name: imagen_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imagen_producto (
    id integer NOT NULL,
    orden integer,
    url_img character varying(500) NOT NULL,
    id_producto integer NOT NULL
);


ALTER TABLE public.imagen_producto OWNER TO postgres;

--
-- Name: imagen_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imagen_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagen_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensaje; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensaje (
    id integer NOT NULL,
    contenido text NOT NULL,
    fecha_envio timestamp(6) without time zone,
    leido boolean NOT NULL,
    id_chat integer NOT NULL
);


ALTER TABLE public.mensaje OWNER TO postgres;

--
-- Name: mensaje_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id integer NOT NULL,
    activo boolean NOT NULL,
    categoria character varying(20) NOT NULL,
    color character varying(20),
    descripcion character varying(500),
    estado character varying(20) NOT NULL,
    estilo character varying(30) NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    fecha_devolucion timestamp(6) without time zone,
    marca character varying(20) NOT NULL,
    precio numeric(10,2),
    talla character varying(4) NOT NULL,
    tipo character varying(50) NOT NULL,
    titulo character varying(50) NOT NULL,
    id_usuario integer NOT NULL,
    CONSTRAINT producto_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('intercambio'::character varying)::text, ('prestamo'::character varying)::text])))
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- Name: producto_historico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_historico (
    id integer NOT NULL,
    accion character varying(255) NOT NULL,
    categoria character varying(20),
    color character varying(20),
    descripcion character varying(500),
    estilo character varying(30),
    fecha_creacion timestamp(6) without time zone,
    fecha_devolucion timestamp(6) without time zone,
    marca character varying(20),
    precio numeric(38,2),
    talla character varying(4),
    tipo character varying(255) NOT NULL,
    titulo character varying(50),
    id_producto integer,
    id_usuario integer,
    CONSTRAINT producto_historico_accion_check CHECK (((accion)::text = ANY (ARRAY[('CREADO'::character varying)::text, ('ACTUALIZADO'::character varying)::text, ('BORRADO'::character varying)::text, ('DESACTIVADO'::character varying)::text]))),
    CONSTRAINT producto_historico_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('intercambio'::character varying)::text, ('prestamo'::character varying)::text])))
);


ALTER TABLE public.producto_historico OWNER TO postgres;

--
-- Name: producto_historico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto_historico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_historico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raiting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.raiting (
    puntuacion integer,
    id_puntuado integer NOT NULL,
    id_puntuador integer NOT NULL
);


ALTER TABLE public.raiting OWNER TO postgres;

--
-- Name: seguidor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguidor (
    id_seguido integer NOT NULL,
    id_seguidor integer NOT NULL
);


ALTER TABLE public.seguidor OWNER TO postgres;

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    apellidos character varying(50) NOT NULL,
    descripcion character varying(500),
    direccion character varying(500),
    email character varying(50) NOT NULL,
    estilo character varying(30),
    nombre character varying(20) NOT NULL,
    password character varying(50) NOT NULL,
    t_calzado integer,
    t_camiseta character varying(4),
    t_pantalon integer,
    url_img character varying(500)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE usuario ALTER COLUMN password TYPE VARCHAR(100);


--
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- Name: favorito favorito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_pkey PRIMARY KEY (id_producto, id_usuario);


--
-- Name: imagen_producto imagen_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagen_producto
    ADD CONSTRAINT imagen_producto_pkey PRIMARY KEY (id);


--
-- Name: mensaje mensaje_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensaje
    ADD CONSTRAINT mensaje_pkey PRIMARY KEY (id);


--
-- Name: producto_historico producto_historico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_historico
    ADD CONSTRAINT producto_historico_pkey PRIMARY KEY (id);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- Name: raiting raiting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raiting
    ADD CONSTRAINT raiting_pkey PRIMARY KEY (id_puntuado, id_puntuador);


--
-- Name: seguidor seguidor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguidor
    ADD CONSTRAINT seguidor_pkey PRIMARY KEY (id_seguido, id_seguidor);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: chat fk47e8sscmkvy9a9kqilweqy3gd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk47e8sscmkvy9a9kqilweqy3gd FOREIGN KEY (id_producto2) REFERENCES public.producto(id);


--
-- Name: chat fk49vc48lf6aievxgo6kc6kmbap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk49vc48lf6aievxgo6kc6kmbap FOREIGN KEY (id_usuario1) REFERENCES public.usuario(id);


--
-- Name: favorito fk5vmlgfa4nyi848sknxb237yjt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT fk5vmlgfa4nyi848sknxb237yjt FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- Name: raiting fk6uhh530phlkfvhd2ivl0t8jeh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raiting
    ADD CONSTRAINT fk6uhh530phlkfvhd2ivl0t8jeh FOREIGN KEY (id_puntuado) REFERENCES public.usuario(id);


--
-- Name: seguidor fk7m5yeae46r7kidkh745j83wt1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguidor
    ADD CONSTRAINT fk7m5yeae46r7kidkh745j83wt1 FOREIGN KEY (id_seguido) REFERENCES public.usuario(id);


--
-- Name: producto_historico fk8n6mcd4dlkbyiu41ayt3qgxfr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_historico
    ADD CONSTRAINT fk8n6mcd4dlkbyiu41ayt3qgxfr FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- Name: producto_historico fkb1kio7fwgafb6foordgu6vlj0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_historico
    ADD CONSTRAINT fkb1kio7fwgafb6foordgu6vlj0 FOREIGN KEY (id_producto) REFERENCES public.producto(id);


--
-- Name: mensaje fke19chdnxesv3itlf0v128hmrp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensaje
    ADD CONSTRAINT fke19chdnxesv3itlf0v128hmrp FOREIGN KEY (id_chat) REFERENCES public.chat(id);


--
-- Name: imagen_producto fkh1jspkou01bp4y2q0ynq9el6k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagen_producto
    ADD CONSTRAINT fkh1jspkou01bp4y2q0ynq9el6k FOREIGN KEY (id_producto) REFERENCES public.producto(id);


--
-- Name: chat fkj8jtvjv92axld94ivb4j92tk2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fkj8jtvjv92axld94ivb4j92tk2 FOREIGN KEY (id_usuario2) REFERENCES public.usuario(id);


--
-- Name: producto fkjhnhu11h92o6gjd4eha5xux79; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkjhnhu11h92o6gjd4eha5xux79 FOREIGN KEY (id_usuario) REFERENCES public.usuario(id);


--
-- Name: chat fklup4frpvgeol2gatg4b74ism4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fklup4frpvgeol2gatg4b74ism4 FOREIGN KEY (id_producto1) REFERENCES public.producto(id);


--
-- Name: favorito fkq7wolabg1djamjksigfuljss2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT fkq7wolabg1djamjksigfuljss2 FOREIGN KEY (id_producto) REFERENCES public.producto(id);


--
-- Name: raiting fksb5xtm5jt7u99dajtnj8lvimi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raiting
    ADD CONSTRAINT fksb5xtm5jt7u99dajtnj8lvimi FOREIGN KEY (id_puntuador) REFERENCES public.usuario(id);


--
-- Name: seguidor fkshauxuejxaiguxm7jlk5bpuej; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguidor
    ADD CONSTRAINT fkshauxuejxaiguxm7jlk5bpuej FOREIGN KEY (id_seguidor) REFERENCES public.usuario(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ESYSQx47dS4pld5hjnYvkGDYaxEaelKjtLcg6uu0l8gUgz6KUiu5c1CgvZygD0U

